### PR TITLE
Update jquery iframe transport to v1.0.1

### LINKED ISSUE #156: Re-submited form missing file
Scenario to reproduce:
- Click link - the form loaded from server
- Fill form with incorrect data but with right file
- Click submit button and get errors
- Fill with correct data and click again.

The first click request:
Processing by Events::EventTracksController#create as JS
`Parameters: {"utf8"=>"✓", "display_raw_results"=>"false", "event_track"=>{"competitor_id"=>"85", "round_id"=>"44", "track_from"=>"from_file", "track_id"=>"", "track_attributes"=>{"file"=>#<ActionDispatch::Http::UploadedFile:0x0055dc644a2518 @tempfile=#<Tempfile:/tmp/RackMultipart20160804-1-oztmcn.JPG>, @original_filename="IMG_2400.JPG", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"event_track[track_attributes][file]\"; filename=\"IMG_2400.JPG\"\r\nContent-Type: image/jpeg\r\n">}}, "commit"=>"Save", "remotipart_submitted"=>"true", "authenticity_token"=>"GlYlOqMIlBK7Gdmt5Zw93QTK9cm20mowL6TZjqvZq0tAVquTlMiwreVfb0sXalxcqBkEpUZguuRlC33FqAHWqg==", "X-Requested-With"=>"IFrame", "X-Http-Accept"=>"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01", "locale"=>"ru", "event_id"=>"12"}`

The second click request:
`Parameters: {"utf8"=>"✓", "display_raw_results"=>"false", "event_track"=>{"competitor_id"=>"85", "round_id"=>"44", "track_from"=>"from_file", "track_id"=>""}, "commit"=>"Сохранить", "locale"=>"ru", "event_id"=>"12"}`

Can't figure out why it's working this way. Why file field gets cleared and not restored after getting error?
Could you please help with my issue?

### PR DESCRIPTION
**Pull request by westonganger**
I was having troubles with multiple file uploads, with files being removed. Upgrading jquery.iframe-transport was the solution. 

This is an important fix.

Fixes #156

### CODE REVIEW

**Comment by sbadura** [comment]
:+1:

**Comment by westonganger** [comment]
@mshibuya can you please merge this. This bug is breaking my apps.

**Comment by phlegx** [comment]
@mshibuya  please merge. Thx!

**Comment by mshibuya** [comment]
Sorry for delay, thanks!

**Comment by mrj** [comment]
Deserves a new Gem release, so developers seeing the multiple-file problem don't have to debug, only to work out that it's fixed if they source Remotipart from Git instead of Rubygems.

**Pull request merged**
