### PR TITLE
jQuery3 compatibility

### PR DESCRIPTION
**Pull request by spdawson**
Do not call complete on object returned from jQuery.ajax; see #161

### CODE REVIEW

**Comment by existent-co-uk** [comment]
This issue is also affecting us; any chance of getting this PR merged, and a new gem version released?

**Comment by spdawson** [comment]
Is there anything I can do to get this merged?

**Comment by clairity** [comment]
thanks @spdawson ! manually implementing this change made remotipart work for me (rails 5.0.1, jquery3).

**Comment by iarie** [comment]
@spdawson i'am using your solution, thanks!  This bug almost made me quit the idea of using remotipart :/ 
ps: rails 5.0.1/ JQuery3

**Comment by pnaponoceno** [comment]
I'm getting a `SyntaxError: missing ; before statement`, any hints on this? Thanks

**Comment by kyle-glick** [comment]
@JangoSteve @mshibuya 
This is a pretty glaring issue nearly 2 years after the release of jQuery 3. If @spdawson 's solution fixes the problem, can this please be merged soon, or at least reviewed? This PR has been up for 1 1/2 years and this issue is affecting many users of `remotipart`.

**Comment by JangoSteve** [comment]
You're right! I'll take a look, merge it, and release a new version.

**Pull request closed without merging**
