### PR TITLE
Integrate feature specs

### PR DESCRIPTION
**Pull request by mshibuya**
Based on: https://github.com/JangoSteve/Rails-jQuery-Demo/tree/remotipart

Will be merged in after @JangoSteve has activated TravisCI build.

### CODE REVIEW

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by mshibuya** [comment]
ping @JangoSteve

**Comment by n-rodriguez** [comment]
https://github.com/jbox-web/remotipart

**Comment by JangoSteve** [comment]
I think I have Travis integrated with the repo. They deprecated "integrations" for new "github apps" so I'm not positive I've done everything I need to. Let me know if anything else needs to be done.

**Comment by mshibuya** [comment]
How wonderful, I can see a build running on travis-ci.com!
https://travis-ci.com/JangoSteve/remotipart/jobs/199877208

**Comment by mshibuya** [comment]
Build passes now, merging in.

**Pull request merged**
