### PR TITLE
Load action_controller lazily

### PR DESCRIPTION
**Pull request by arr-dev**
Fixes deprecation notice
https://github.com/rails/rails/issues/36546

### CODE REVIEW

**Comment by arr-dev** [comment]
Failures are caused by Sprockets 4, so either `manifest.js` should be added or sprockets should be downgraded to `< 4`, not sure what's the preferred option?

**Comment by vdegove** [comment]
Fixes #207 I had opened the issue without seeing the PR.

**Comment by vdegove** [comment]
> Failures are caused by Sprockets 4, so either `manifest.js` should be added or sprockets should be downgraded to `< 4`, not sure what's the preferred option?

@arr-dev it seems the correct way to go is to define assets for precompilation in engine.rb: https://guides.rubyonrails.org/engines.html#separate-assets-precompiling See discussion here: https://github.com/rails/sprockets/issues/415

**Comment by arr-dev** [comment]
Adding manifest solved these failures, but app still needs to manually require jquery.remotipart, no changes there.

**Comment by mshibuya** [comment]
Great work, thanks!

**Pull request merged**
